### ISSUE TITLE
请问，登录后需要短信验证码如何输入呢？

### ISSUE THREAD

**Issue by devadapter** [libra146/docker-topsap#13]

**Comment by libra146** [comment]
目前还没支持验证码自动输入，可以在容器里面手动输入，但是比较麻烦，而且容易失败，这块我还在考虑解决方案，如果有大佬有办法解决，欢迎 PR

**Comment by devadapter** [comment]
> 目前还没支持验证码自动输入，可以在容器里面手动输入，但是比较麻烦，而且容易失败，这块我还在考虑解决方案，如果有大佬有办法解决，欢迎 PR

容器里如何手动输入，是执行一遍 ./start.sh 吗？请问如何将系统流量代理到容器内的网络。

**Comment by libra146** [comment]
> > 目前还没支持验证码自动输入，可以在容器里面手动输入，但是比较麻烦，而且容易失败，这块我还在考虑解决方案，如果有大佬有办法解决，欢迎 PR
> 
> 容器里如何手动输入，是执行一遍 ./start.sh 吗？请问如何将系统流量代理到容器内的网络。

手动使用 exec 进入容器，然后手动执行 start.sh，并且输入验证码，这个过程中可能会有部分报错，这块不太稳定，我还在尝试解决
关于如何将系统流量导入容器还请根据自己的网络环境尝试使用代理软件，将流量导入到 docker 容器暴露的端口即可

**Comment by devadapter** [comment]
> > > 目前还没支持验证码自动输入，可以在容器里面手动输入，但是比较麻烦，而且容易失败，这块我还在考虑解决方案，如果有大佬有办法解决，欢迎 PR
> > 
> > 容器里如何手动输入，是执行一遍 ./start.sh 吗？请问如何将系统流量代理到容器内的网络。
> 
> 手动使用 exec 进入容器，然后手动执行 start.sh，并且输入验证码，这个过程中可能会有部分报错，这块不太稳定，我还在尝试解决
> 关于如何将系统流量导入容器还请根据自己的网络环境尝试使用代理软件，将流量导入到 docker 容器暴露的端口即可

进入容器登录的过程已经完成，请问使用代理软件将流量导入到docker有教程吗，如果有，麻烦您贴一下,非常感谢。

**Comment by libra146** [comment]
> > > > 目前还没支持验证码自动输入，可以在容器里面手动输入，但是比较麻烦，而且容易失败，这块我还在考虑解决方案，如果有大佬有办法解决，欢迎 PR
> > > 
> > > 
> > > 容器里如何手动输入，是执行一遍 ./start.sh 吗？请问如何将系统流量代理到容器内的网络。
> > 
> > 
> > 手动使用 exec 进入容器，然后手动执行 start.sh，并且输入验证码，这个过程中可能会有部分报错，这块不太稳定，我还在尝试解决
> > 关于如何将系统流量导入容器还请根据自己的网络环境尝试使用代理软件，将流量导入到 docker 容器暴露的端口即可
> 
> 进入容器登录的过程已经完成，请问使用代理软件将流量导入到docker有教程吗，如果有，麻烦您贴一下,非常感谢。

这块的话还是要自己找一下吧，因为不知道你用的什么软件，浏览器还是客户端软件，还有要每个软件设置代理的方式都不一样

**Comment by devadapter** [comment]
我是windows系统，使用浏览器代理应该怎么做？现在遇到新的问题，进入容器内登录成功后，无法ssh连接到内网服务器，wget、curl都是能正常访问内网服务器的，请问是ssh需要代理还是什么的嘛？

**Comment by libra146** [comment]
> 我是windows系统，使用浏览器代理应该怎么做？现在遇到新的问题，进入容器内登录成功后，无法ssh连接到内网服务器，wget、curl都是能正常访问内网服务器的，请问是ssh需要代理还是什么的嘛？

浏览器的话可以在 windows 系统代理哪里设置
<img width="898" alt="image" src="https://github.com/libra146/docker-topsap/assets/17448639/c0f75805-4da9-4d5f-b5a2-0f8b7f94f364">
ssh 的话也不用单独设置代理了，暂时还没有对 windows 做过兼容性测试，可能是 windows 下 iptables 有兼容问题
