### ISSUE TITLE
好像是danted的问题  容器内可以正常访问 但是端口映射不出去

### ISSUE THREAD

**Issue by onlyweek** [libra146/docker-topsap#14]
![image](https://github.com/libra146/docker-topsap/assets/55268911/952756bf-7059-429f-9ce1-1ff572a50f2b)
好像1080端口已经打开了 但是好像danted服务还没有起来
![image](https://github.com/libra146/docker-topsap/assets/55268911/1c3e6ca1-39b2-454e-b89d-d5d6a7034440)
而且在执行start.sh的时候 
![image](https://github.com/libra146/docker-topsap/assets/55268911/e7fd076b-f054-48b0-b783-42cac9321cfc)
显示登录成功后就会卡死   看了文件 应该就是 danted -f /etc/danted.conf &这个的问题
大佬们，能帮忙看下吗

**Comment by onlyweek** [comment]
![image](https://github.com/libra146/docker-topsap/assets/55268911/b99430aa-8514-4d12-87fc-9f2bb1337b93)
好像上面图片不是全的  再补充一个

**Comment by onlyweek** [comment]
Login Success!
Jan 10 02:39:43 (1704854383.263063) danted[179]: warning: could not open pidfile /var/run/danted.pid for writing: Permission denied
Jan 10 02:39:43 (1704854383.408326) danted[179]: info: Dante/server[1/1] v1.4.2 running
--------------------------------------------------------------------------------------------------
最后好像提示了这个 但是还是不能从外部用socks访问
是需要专门设置一个用户权限吗

**Comment by libra146** [comment]
最后提示的警告没有影响，服务的话应该是没有用 systemctl 启动，所以直接查询会提示没有启动，你看看实际服务进程在不在？

**Comment by onlyweek** [comment]
> 最后提示的警告没有影响，服务的话应该是没有用 systemctl 启动，所以直接查询会提示没有启动，你看看实际服务进程在不在？

这个好像容器内我看没有systemctl，我用的是直接拉的docker.io里面的镜像，所以只能用service去查看

**Comment by libra146** [comment]
> > 最后提示的警告没有影响，服务的话应该是没有用 systemctl 启动，所以直接查询会提示没有启动，你看看实际服务进程在不在？
> 
> 这个好像容器内我看没有systemctl，我用的是直接拉的docker.io里面的镜像，所以只能用service去查看

嗯嗯，只要进程在端口在监听就可以

**Comment by onlyweek** [comment]
> > > 最后提示的警告没有影响，服务的话应该是没有用 systemctl 启动，所以直接查询会提示没有启动，你看看实际服务进程在不在？
> > 
> > 
> > 这个好像容器内我看没有systemctl，我用的是直接拉的docker.io里面的镜像，所以只能用service去查看
> 
> 嗯嗯，只要进程在端口在监听就可以

好嘞  那这个已经解决了 非常感谢

**Comment by libra146** [comment]
> > > > 最后提示的警告没有影响，服务的话应该是没有用 systemctl 启动，所以直接查询会提示没有启动，你看看实际服务进程在不在？
> > > 
> > > 
> > > 这个好像容器内我看没有systemctl，我用的是直接拉的docker.io里面的镜像，所以只能用service去查看
> > 
> > 
> > 嗯嗯，只要进程在端口在监听就可以
> 
> 好嘞 那这个已经解决了 非常感谢

好的，那 issues 我就先关闭了哈
