### ISSUE TITLE
Duplicated work (alternative?)

### ISSUE THREAD

**Issue by inclyc** [libra146/docker-topsap#4]
乐，最近整了个类似的 https://github.com/inclyc/containerized-topsap

我直接解压 deb 包，没安装，他那里面一大堆灵车脚本（

**Comment by libra146** [comment]
很好的思路，不用安装也不错~

**Comment by inclyc** [comment]
其实有用的文件就这三个，别的全是乱七八糟的软件垃圾

https://github.com/inclyc/containerized-topsap/blob/93d7f84dd51288da35645b8f3dc5e2035a22a756/Containerfile#L16-L18

**Comment by inclyc** [comment]
他这程序非要把运行时生成的数据 (server.key server.pem) 放到 pwd ，同时还要依赖 pwd 下的 libvpn_client.so 就挺离谱的

**Comment by inclyc** [comment]
我这个没怎么管 UUID 的事情 <del>能用就行</del>

**Comment by libra146** [comment]
> 他这程序非要把运行时生成的数据 (server.key server.pem) 放到 pwd ，同时还要依赖 pwd 下的 libvpn_client.so 就挺离谱的

哈哈哈，动不动路径不对就给你一个 not found

**Comment by libra146** [comment]
> 我这个没怎么管 UUID 的事情 ~能用就行~

因为公司对这个有限制，不能绑定太多机器
