### ISSUE TITLE
怎么使用 clash 配置代理呢

### ISSUE THREAD

**Issue by tudan110** [libra146/docker-topsap#7]
大佬，怎么使用 clash 配置代理呢

**Comment by libra146** [comment]
> 

如果你按照教程做，默认会监听 本地的 1088 端口，将代理指向本地的 1088 端口即可，具体参考你使用的软件

**Comment by tudan110** [comment]
> > 
> 
> 如果你按照教程做，默认会监听 本地的 1088 端口，将代理指向本地的 1088 端口即可，具体参考你使用的软件

感谢，可以使用了
