### ISSUE TITLE
输入完服务器地址后，返回 The Client Server is NOT Started

### ISSUE THREAD

**Issue by tudan110** [libra146/docker-topsap#8]
Welcome Login Mode!

Input your server address(example:192.168.74.12:8112): 106.120.220.78:8000

The Client Server is NOT Started.
 Please start the Client Server first!

**Comment by tudan110** [comment]
Client Server 是什么

**Comment by libra146** [comment]
> Welcome Login Mode! 欢迎登录模式！
> 
> Input your server address(example:192.168.74.12:8112): 106.120.220.78:8000输入您的服务器地址（例如：192.168.74.12:8112）：106.120.220.78:8000
> 
> The Client Server is NOT Started.客户端服务器未启动。 Please start the Client Server first! 请先启动客户端服务器！

正常启动的话应该不会报这个错误，你是怎么执行的？使用的哪个版本的镜像？

**Comment by tudan110** [comment]
抱歉，我没说清楚，用 docker 启动镜像可以正常运行，浏览器里使用 SwitchyOmega 插件代理，socks5 127.0.0.1 1088，发现有个别内网地址无法访问。
我想着直接在 manjaro 系统里安装 TopSAP-3.5.2.36.2-x86_64.deb 这个软件包来使用。有时候可以正常登录，有时候会报 “The Client Server is NOT Started.
Please start the Client Server first!” 这个。
大佬知道原因嘛

**Comment by libra146** [comment]
> 

额，看你的 mac 是什么架构的，如果是 arm 的话需要下载 arm 版本的软件包

还有这个提示的意思是服务器没启动，这个需要根据你的 mac 系统情况来排查了，看看服务端是为什么没有启动

还是推荐使用 docker 来运行，可以排除环境的影响，如果有部分内网地址没有使用代理的话，可以检查下SwitchyOmega插件中的规则是否让所有需要代理的地址走代理了

**Comment by tudan110** [comment]
电脑是 x86 的，前几天可以正常用，有时候冒出这个错误，过一会儿会变好，今天遇到后，重启了好几次电脑，也没能正常。我再研究用 docker 代理试试，谢谢啦

**Comment by libra146** [comment]
> 电脑是 x86 的，前几天可以正常用，有时候冒出这个错误，过一会儿会变好，今天遇到后，重启了好几次电脑，也没能正常。我再研究用 docker 代理试试，谢谢啦

topsap 有 GUI 版本的软件包的，可以到官网去找找，如果想要直接使用宿主机的话可以安装 GUI 版本的，比较方便使用，不用命令行，命令行版适合在 docker 中使用

**Comment by tudan110** [comment]
https://app.topsec.com.cn/ng.html

有 linux 版本的 gui 嘛，没找到

![image](https://github.com/libra146/docker-topsap/assets/29975209/3575e682-57a0-432c-9e0d-51402dd56613)

**Comment by tudan110** [comment]
或者他这个就是 gui，安装完确实在桌面上创建了个图标，但是在 manjaro 上，gui起不来

**Comment by libra146** [comment]
> https://app.topsec.com.cn/ng.html
> 
> 有 linux 版本的 gui 嘛，没找到
> 
> ![image](https://user-images.githubusercontent.com/29975209/254499201-3575e682-57a0-432c-9e0d-51402dd56613.png)

🤣你不是mac 吗，用 mac 的呀

**Comment by tudan110** [comment]
不是mac，是 dell 灵越 7590

**Comment by libra146** [comment]
> 或者他这个就是 gui，安装完确实在桌面上创建了个图标，但是在 manjaro 上，gui起不来

 🤣不好意思看错了，我以为 mac 系统，linux 好像我还真没用过 GUI 版，还是用命令行吧

**Comment by tudan110** [comment]
嗯嗯，不知道是不是昨晚上更新系统出问题了，晚上回家再研究一下
